routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function (){

    Route::group(['prefix' => 'auth', 'middleware' => ['usernameUUID']], function (){

        Auth::routes(['verify' => true]);

        Route::post('/twofa/authenticate', 'Auth\TwofaController@verify2FA')
            ->name('verify2FA');

    });

    Route::get('/','HomeController@index')
        ->middleware('eligibility');

    Route::post('/form/contact', 'ContactController@create')
        ->name('sendSubmission');


    Route::group(['middleware' => ['auth', 'forcelogout', '2fa', 'verified']], function(){

        Route::get('/dashboard', 'DashboardController@index')
            ->name('dashboard')
            ->middleware('eligibility');

        Route::get('users/directory', 'ProfileController@index')
            ->name('directory');

        Route::group(['prefix' => '/applications'], function (){

            Route::get('/my-applications', 'ApplicationController@showUserApps')
                ->name('showUserApps')
                ->middleware('eligibility');

            Route::get('/view/{application}', 'ApplicationController@showUserApp')
                ->name('showUserApp');

            Route::post('/{application}/comments', 'CommentController@insert')
                ->name('addApplicationComment');

            Route::delete('/comments/{comment}/delete', 'CommentController@delete')
                ->name('deleteApplicationComment');


            Route::patch('/notes/save/{application}', 'AppointmentController@saveNotes')
                ->name('saveNotes');


            Route::patch('/update/{application}/{newStatus}', 'ApplicationController@updateApplicationStatus')
                ->name('updateApplicationStatus');

            Route::delete('{application}/delete', 'ApplicationController@delete')
                ->name('deleteApplication');


            Route::get('/staff/all', 'ApplicationController@showAllApps')
                ->name('allApplications');


            Route::get('/staff/outstanding', 'ApplicationController@showAllPendingApps')
                ->name('staffPendingApps');


            Route::get('/staff/peer-review', 'ApplicationController@showPeerReview')
                ->name('peerReview');


            Route::get('/staff/pending-interview', 'ApplicationController@showPendingInterview')
                ->name('pendingInterview');



            Route::post('{application}/staff/vote', 'VoteController@vote')
                ->name('voteApplication');


        });

        Route::group(['prefix' => 'appointments'], function (){

            Route::post('schedule/appointments/{application}', 'AppointmentController@saveAppointment')
                ->name('scheduleAppointment');

            Route::patch('update/appointments/{application}/{status}', 'AppointmentController@updateAppointment')
                ->name('updateAppointment');

        });

        Route::group(['prefix' => 'apply', 'middleware' => ['eligibility']], function (){

            Route::get('positions/{vacancySlug}', 'ApplicationController@renderApplicationForm')
                ->name('renderApplicationForm');

            Route::post('positions/{vacancySlug}/submit', 'ApplicationController@saveApplicationAnswers')
                ->name('saveApplicationForm');

        });

        Route::group(['prefix' => '/profile'], function (){

            Route::get('/settings', 'ProfileController@showProfile')
                ->name('showProfileSettings');

            Route::patch('/settings/save', 'ProfileController@saveProfile')
                ->name('saveProfileSettings');

            Route::get('user/{user}', 'ProfileController@showSingleProfile')
                ->name('showSingleProfile');


            Route::get('/settings/account', 'UserController@showAccount')
                ->name('showAccountSettings');


            Route::patch('/settings/account/change-password', 'UserController@changePassword')
                ->name('changePassword');

            Route::patch('/settings/account/change-email', 'UserController@changeEmail')
                ->name('changeEmail');

            Route::post('/settings/account/flush-sessions', 'UserController@flushSessions')
                ->name('flushSessions');

            Route::patch('/settings/account/twofa/enable', 'UserController@add2FASecret')
                ->name('enable2FA');

            Route::patch('/settings/account/twofa/disable', 'UserController@remove2FASecret')
                ->name('disable2FA');

        });


        Route::group(['prefix' => '/hr'], function (){

            Route::get('staff-members', 'UserController@showStaffMembers')
                ->name('staffMemberList');

            Route::get('players', 'UserController@showPlayers')
                ->name('registeredPlayerList');

            Route::post('players/search', 'UserController@showPlayersLike')
                ->name('searchRegisteredPLayerList');

            Route::patch('staff-members/terminate/{user}', 'UserController@terminate')
                ->name('terminateStaffMember');

        });

        Route::group(['prefix' => 'admin'], function (){

            Route::get('settings', 'OptionsController@index')
                ->name('showSettings');

            Route::post('settings/save', 'OptionsController@saveSettings')
                ->name('saveSettings');

            Route::post('players/ban/{user}', 'BanController@insert')
                ->name('banUser');

            Route::delete('players/unban/{user}', 'BanController@delete')
                ->name('unbanUser');



            Route::delete('players/delete/{user}', 'UserController@delete')
                ->name('deleteUser');

            Route::patch('players/update/{user}', 'UserController@update')
                ->name('updateUser');



            Route::get('positions', 'VacancyController@index')
                ->name('showPositions');

            Route::post('positions/save', 'VacancyController@store')
                ->name('savePosition');


            Route::get('positions/edit/{vacancy}', 'VacancyController@edit')
                ->name('editPosition');

            Route::patch('positions/update/{vacancy}', 'VacancyController@update')
                ->name('updatePosition');


            Route::patch('positions/availability/{status}/{vacancy}', 'VacancyController@updatePositionAvailability')
                ->name('updatePositionAvailability');


            Route::get('forms/builder', 'FormController@showFormBuilder')
                ->name('showFormBuilder');

            Route::post('forms/save', 'FormController@saveForm')
                ->name('saveForm');

            Route::delete('forms/destroy/{form}', 'FormController@destroy')
                ->name('destroyForm');

            Route::get('forms', 'FormController@index')
                ->name('showForms');

            Route::get('forms/preview/{form}', 'FormController@preview')
                ->name('previewForm');

            Route::get('forms/edit/{form}', 'FormController@edit')
                ->name('editForm');

            Route::patch('forms/update/{form}', 'FormController@update')
                ->name('updateForm');


            Route::get('devtools', 'DevToolsController@index')
                ->name('devTools');

            // we could use route model binding
            Route::post('devtools/vote-evaluation/force', 'DevToolsController@forceVoteCount')
                ->name('devToolsForceVoteCount');

        });

    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'originalIP', 'username', 'uuid', 'dob'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


//
    public function applications()
    {
        return $this->hasMany('App\Application', 'applicantUserID', 'id');
    }

    public function votes()
    {
        return $this->hasMany('App\Vote', 'userID', 'id');
    }

    public function profile()
    {
        return $this->hasOne('App\Profile', 'userID', 'id');
    }

    public function bans()
    {
        return $this->hasOne('App\Ban', 'userID', 'id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment', 'authorID', 'id');
    }


    public function isBanned()
    {
        return !$this->bans()->get()->isEmpty();
    }




    public function isStaffMember()
    {
        return $this->hasAnyRole('reviewer', 'admin', 'hiringManager');
    }

    public function has2FA()
    {
        return !is_null($this->twofa_secret);
    }



    public function routeNotificationForSlack($notification)
    {
       return config('slack.webhook.integrationURL');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Vacancy;
use App\User;
use App\Ban;
use App\Application;

class DashboardController extends Controller
{

    public function index()
    {
        $totalPeerReview = Application::where('applicationStatus', 'STAGE_PEERAPPROVAL')->get()->count();
        $totalNewApplications = Application::where('applicationStatus', 'STAGE_SUBMITTED')->get()->count();
        $totalDenied = Application::where('applicationStatus', 'DENIED')->get()->count();

        return view('dashboard.dashboard')
            ->with([
              'vacancies' => Vacancy::all(),
              'totalUserCount' => User::all()->count(),
              'totalDenied' => $totalDenied,
              'totalPeerReview' => $totalPeerReview,
              'totalNewApplications' => $totalNewApplications
            ]);

    }

}

resources/views/dashboard/administration/devtools.blade.php
@extends('adminlte::page')

@section('title', config('app.name') . ' | ' . __('messages.devoptions'))

@section('content_header')

    <h4>{{__('messages.adm')}} / {{__('messages.devtools')}}</h4>

@stop

@section('js')
    <x-global-errors></x-global-errors>
@stop

@section('content')

    <x-modal id="confirmForceEventDispatch" modal-label="confirmForceEventDispatch" modal-title="{{__('messages.choose_app')}}" include-close-button="true">

        <p>{{__('messages.forceeval')}}</p>
        <form method="POST" id="forceEval" action="{{route('devToolsForceVoteCount')}}">
            @csrf
            <select name="application" class="custom-select">
                @if(!$applications->isEmpty())
                    @foreach($applications as $application)

                        <option value="{{$application->id}}">{{__('messages.appid')}} {{$application->id}} ({{$application->user->name}})</option>

                    @endforeach
                @else
                    <option value="null" disabled>{{__('messages.no_valid_app')}}</option>
                @endif
            </select>

        </form>

        <x-slot name="modalFooter">
            <button type="button" class="btn btn-danger" onclick="document.getElementById('forceEval').submit()">{{__('messages.dispatch_event')}}</button>
        </x-slot>

    </x-modal>

    <div class="row">
        <div class="col">

            <div class="alert alert-warning">

                <i class="fa fa-exclamation-triangle"></i> <b>{{__('messages.warn')}}</b>
                <p>{{__('messages.devtools_warn')}}</p>
            </div>

        </div>
    </div>

    <div class="row">

        <div class="col">

            <x-card id="tools" card-title="{{__('messages.devtools_evn')}}" footer-style="text-center">

                <x-slot name="cardHeader">

                </x-slot>
                    <button type="button" class="btn btn-danger" onclick="$('#confirmForceEventDispatch').modal('show')">{{__('messages.override_votes')}}</button>
                    <button type="button" class="btn btn-warning ml-3">{{__('messages.artisan_evaluate')}}</button>

                <x-slot name="cardFooter">
                    <p class="text-muted"> .</p>
                </x-slot>
            </x-card>

        </div>

    </div>

@stop

@section('footer')
    @include('breadcrumbs.dashboard.footer')
@stop

resources/views/dashboard/administration/editform.blade.php
@extends('adminlte::page')

@section('title', 'Raspberry Network | Edit From')

@section('content_header')

    <h4>{{__('messages.adm')}} / {{__('messages.forms')}} / {{__('messages.edt')}}</h4>

@stop

@section('js')

  <script src="/js/formeditor.js"></script>
  <x-global-errors></x-global-errors>

@stop

@section('content')

  <div class="row mb-5">
    <div class="col">

    </div>
    <div class="col text-center">

      <img src="/img/editor.svg" width="250px" alt="Editor illustration" class="img-responsive" />

    </div>
    <div class="col">

    </div>
  </div>


  <div class="row">

    <div class="col">


    </div>
    <div class="col">

      <form id="editForm" method="POST" action="{{ route('updateForm', ['form' => $formID]) }}">
        @csrf
        @method('PATCH')
          <div class="card">

            <div class="card-header">

              <h4>{{__('messages.edt_action')}} {{ $title }}...</h4>

            </div>

            <div class="card-body">

              @foreach($formStructure['fields'] as $fieldName => $field)

                <div class="form-group mt-4 mb-4">

                    <input autocomplete="false" type="text" id="{{ $fieldName }}" class="form-control" name="{{ $fieldName }}[]" value="{{ $field['title'] }}" />

                    <select class="custom-select" id="{{ $fieldName }}-type" name="{{ $fieldName }}[]">

                        <option value="nil" disabled>{{__('messages.field_type')}}</option>
                        <option value="textbox" {{ ($field['type'] == 'textbox' ? 'selected' : '') }}>{{__('messages.txtbox')}}</option>
                        <option value="textarea" {{ ($field['type'] == 'textarea' ? 'selected' : '') }}>{{__('messages.multiline')}}</option>
                        <option value="checkbox" {{ ($field['type'] == 'checkbox' ? 'selected' : '') }}>{{__('messages.checkbox')}}</option>

                    </select>

                </div>

              @endforeach

              <div class="field-container mt-4 mb-4">



              </div>

            </div>

            <div class="card-footer text-center">

              <button type="button" class="btn btn-warning ml-2" onclick="$('#editForm').submit()"><i class="fas fa-save"></i> {{__('messages.save_exit')}}</button>
              <button type="button" class="btn btn-primary ml-2" id="add"><i class="fas fa-plus"></i> {{__('messages.new_field')}}</button>

            </div>


          </div>

      </form>

    </div>

    <div class="col">

    </div>

  </div>

@stop

@section('footer')
    @include('breadcrumbs.dashboard.footer')
@stop

resources/views/dashboard/administration/editposition.blade.php
@extends('adminlte::page')

@section('title', 'Raspberry Network | Edit Positions')

@section('content_header')

    <h4>{{__('messages.adm')}} / {{__('messages.positions')}} / {{__('messages.edit')}}</h4>

@stop

@section('js')

  <x-global-errors>

  </x-global-errors>

@stop


@section('content')


  <div class="row">

    <div class="col center">

        <h3>{{__('messages.vacancy_edit')}}</h3>

    </div>

  </div>


  <div class="row">


    <div class="col">


      <div class="card">


        <div class="card-header">

            <h3 class="card-title"><i class="fas fa-clipboard"></i> {{ $vacancy->vacancyName }}</h3>

        </div>


        <div class="card-body">

          <p class="text-muted"><i class="fas fa-question-circle"></i> {{__('messages.form_consistency')}}</p>

          <form method="POST" id="editPositionForm" action="{{ route('updatePosition', ['vacancy' => $vacancy->id]) }}">

            @csrf
            @method('PATCH')

            <div class="row">

              <div class="col">


                <label for="vacancyName">{{__('messages.vacancy.name')}}</label>
                <input type="text" value="{{ $vacancy->vacancyName }}" class="form-control" disabled />

              </div>

              <div class="col">

                <label for="vacancyDescription">{{__('messages.vacancy.description')}}</label>
                <input type="vacancyDescription" class="form-control" name="vacancyDescription" value="{{ $vacancy->vacancyDescription }}" />


              </div>

            </div>

            <div class="row">

              <div class="col">

                <!-- skipping the accessor for obvious reasons -->
                <label for="vacanyDetails">{{__('messages.vacancy.details')}}</label>
                <textarea name="vacancyFullDescription" class="form-control" placeholder="{{ (is_null($vacancy->vacancyFullDescription)) ? __('messages.vacancy.no_details') : '' }}" rows="20">{{ $vacancy->getAttributes()['vacancyFullDescription'] }}</textarea>
                <span class="text-muted"><i class="fab fa-markdown"></i> {{__('messages.vacancy.markdown')}}</span>

              </div>

            </div>

            <div class="row">

              <div class="col">

                <label for="permissionGroupName">{{__('messages.vacancy.permission_group')}}</label>
                <input type="text" class="form-control" value="{{ $vacancy->permissionGroupName }}" id="permissionGroupName" disabled />

              </div>

              <div class="col">

                <label for="discordRoleID">{{__('messages.vacancy.discord_roleid')}}</label>
                <input type="text" class="form-control" value="{{ $vacancy->discordRoleID }}" id="discordRoleID" disabled />


              </div>
            </div>

            <div class="row">

              <div class="col">

                <label for="currentForm">{{__('messages.vacancy.current_form')}}</label>
                <input type="text" class="form-control" value="{{ $vacancy->forms->formName }}" id="currentForm" disabled />

                <label for="remainingSlots">{{__('messages.vacancy.remaining_slots')}}</label>
                <input type="text" class="form-control" value="{{ $vacancy->vacancyCount }}" id="remainingSlots" name="vacancyCount" />


              </div>

            </div>

          </form>

        </div>

        <div class="card-footer">

          <button type="button" class="btn btn-warning" onclick="$('#editPositionForm').submit()"><i class="fas fa-edit"></i> {{__('messages.vacancy.save')}}</button>
          <button type="button" class="btn btn-danger" onclick="window.location.href='{{ route('showPositions') }}'"><i class="fas fa-times"></i> {{__('messages.vacancy.cancel')}}</button>

          @if($vacancy->vacancyStatus == 'OPEN')

            <form method="POST" action="{{ route('updatePositionAvailability', ['vacancy' => $vacancy->id, 'status' => 'close']) }}" style="display: inline">
              @method('PATCH')
              @csrf
              <button type="submit" class="ml-4 btn btn-danger"><i class="fas fa-ban"></i> {{__('messages.vacancy.close_vacancy')}}</button>
            </form>

          @endif

        </div>


      </div>


    </div>

  </div>


@stop

@section('footer')
    @include('breadcrumbs.dashboard.footer')
@stop

resources/views/dashboard/administration/formbuilder.blade.php
@extends('adminlte::page')

@section('title',  config('app.name') . '| ' . __('messages.form_builder.builder_name'))

@section('content_header')

    <h4>{{__('messages.adm')}} / {{__('messages.form_builder.builder')}}</h4>

@stop

@section('js')

    @if (session()->has('success'))

        <script>
            toastr.success("{{session('success')}}")
        </script>

    @elseif(session()->has('error'))

        @foreach(session('error') as $error)

            <script>
                toastr.error("{{session('error')}}")
            </script>

        @endforeach

    @endif

@stop

@section('content')

    <div class="row">

        <div class="col-md-5 offset-md-3">

            <div class="card">

                <div class="card-body">

                    <form id="formbuilder" action="{{route('saveForm')}}" method="POST">

                        @csrf

                        <fieldset id="buildyourform">
                            <legend class="text-center">{{__('messages.form_builder.builder')}}</legend>

                            <input type="text" name="formName" class="form-control mb-5" placeholder="{{__('messages.form_builder.name_form')}}" required>

                        </fieldset>

                    </form>

                </div>

                <div class="card-footer text-center">

                    <button onclick="save()" type="button" class="btn btn-success">{{__('messages.form_builder.save_form')}}</button>
                    <input type="button" value="{{__('messages.new_field')}}" class="add btn btn-info ml-3" id="add" />


                </div>

            </div>

        </div>

    </div>

@stop

@section('footer')
    @include('breadcrumbs.dashboard.footer')
@stop

resources/views/dashboard/administration/formpreview.blade.php
@extends('adminlte::page')

@section('title', config('app.name') . ' | ' . __('messages.form_preview.title'))

@section('content_header')

    <h4>{{__('messages.adm')}} / {{__('messages.form_builder.builder')}} / {{__('messages.form_preview.preview')}}</h4>

@stop


@section('js')

  <x-global-errors></x-global-errors>

@stop


@section('content')

  <div class="row">

      <div class="col-6 offset-4">

        <img src="/img/preview.svg" width="250px" alt="Form preview illustration" />

      </div>

  </div>

  <div class="row mt-4">

    <div class="col">
      <div class="alert alert-success">

        <h5><i class="fas fa-eye"></i> {{__('messages.form_preview.looks')}}</h5>

        <p>
          {{__('messages.form_preview.f_info')}}
        </p>

      </div>
    </div>

  </div>

  <div class="row">

    <div class="col">

      <div class="card">

        <div class="card-header">

          <h3>{{ $title }} - {{__('messages.form')}}</h2>

        </div>

        <div class="card-body">

          @component('components.form', ['form' => $form, 'disableFields' => true])

          @endcomponent

        </div>

        <div class="card-footer text-center">

          <button type="button" class="btn btn-success ml-2" onclick="window.location.href='{{ route('showForms') }}'"><i class="fas fa-chevron-left"></i> {{__('messages.back')}}</button>
          <button type="button" class="btn btn-warning ml-2" onclick="window.location.href='{{ route('editForm', ['form' => $formID]) }}'"><i class="far fa-edit"></i> {{__('messages.edit')}}</button>
        </div>

      </div>

    </div>

  </div>

@stop

@section('footer')
    @include('breadcrumbs.dashboard.footer')
@stop

resources/views/dashboard/administration/players.blade.php
@extends('adminlte::page')

@section('title', config('app.name') . ' | ' . __('messages.players.reg_players'))

@section('content_header')

    <h4>{{__('messages.adm')}} / {{__('messages.players.reg_players')}}</h4>

@stop

@section('js')

    <x-global-errors></x-global-errors>

@stop

@section('content')

    <div class="row">

        <div class="col">
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{$users->count()}}</h3>

                    <p>{{__('messages.players.reg_players')}}</p>
                </div>
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
            </div>
        </div>

        <div class="col">

            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>{{$bannedUserCount}}</h3>

                    <p>{{__('messages.players.total_banned')}}</p>
                </div>
                <div class="icon">
                    <i class="fa fa-ban"></i>
                </div>
            </div>

        </div>
    </div>
I

    <div class="row">

        <div class="col-md-4 offset-md-4">

            <div class="card">

                <div class="card-header">
                    <div class="card-title"><h4><i class="fas fa-search"></i>{{__('messages.players.search')}}</h4></div>
                </div>

                <div class="card-body">

                    <form name="search" method="POST" action="{{route('searchRegisteredPLayerList')}}">
                        @csrf
                        <div class="input-group">
                            <input type="text" name="searchTerm" class="form-control" placeholder="{{__('messages.players.f_p_search')}}">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>

                    </form>

                </div>

            </div>

        </div>

    </div>


    <div class="row mt-5">

        <div class="col">

            <div class="alert alert-warning">
                <p>{{__('messages.players.p_disclaimer')}}</p>
            </div>

        </div>

    </div>


    <div class="row">

        <div class="col">

          <div class="card bg-gray-dark">

              <div class="card-header bg-indigo">

                  <div class="card-title"><h4 class="text-bold">{{__('messages.players.listing')}}</h4></div>

              </div>

              <div class="card-body">
                @if (!$users->isEmpty())
                  <table class="table table-borderless table-active">

                      <thead>
                      <tr>
                          <th>#</th>
                          <th>{{__('messages.players.ign')}}</th>
                          <th>UUID</th>
                          <th>{{__('messages.contactlabel_email')}}</th>
                          <th>{{__('messages.reusable.status')}}</th>
                          <th>{{__('messages.players.reg_date')}}</th>
                          <th>{{__('messages.reusable.actions')}}</th>
                      </tr>
                      </thead>

                      <tbody>

                          @foreach($users as $user)

                            <tr>
                                <td>{{$user->id}}</td>
                                <td>{{UUID::toUsername($user->uuid)}}</td>
                                <td>{{$user->uuid}}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @if ($user->isBanned())
                                        <span class="badge badge-danger"><i class="fa fa-ban"></i> {{__('messages.players.banned')}}</span>
                                    @else
                                        <span class="badge badge-success">{{__('messages.players.active')}}</span>
                                    @endif
                                </td>
                                <td>{{$user->created_at}}</td>
                                <td>
                                  <button type="button" class="btn btn-sm btn-success" onclick="window.location.href='{{route('showSingleProfile', ['user' => $user->id])}}'"><i class="fa fa-eye"></i></button>
                              </td>
                            </tr>

                          @endforeach

                      </tbody>

                  </table>
                @else
                    <div class="alert alert-secondary">

                        <i class="fas fa-question"></i><span> {{__('messages.players.no_reg')}}</span>
                        <p>
                            {{__('messages.players.no_reg_exp')}}
                        </p>

                    </div>
                @endif
              </div>

              <div class="card-footer">

                  <button type="button" class="btn btn-outline-primary" onclick="window.location.href='{{route("staffMemberList")}}'">{{__('messages.players.see_staff')}}</button>

              </div>

          </div>

        </div>

    </div>

@stop

@section('footer')
    @include('breadcrumbs.dashboard.footer')
@stop